apt_proxy: host:port # leave blank to not use apt proxy. if use vpn its better to user ipaddress (can interfere with vpn)
default_user: me # default user, use this user to make kali fun things
git_user: # your git user
git_email: # git email
timezone: Europe/Paris # timezone
vpn_ip_pattern: 192.168 # if vpn is activated, this is a pattern to get the IP, usefull for the set_victim script, that set an ip for a CTF
vpn_name: # blank or absent to not use vpn, if not blank, you must add a file with {{ vpn_name }}.conf in openvpn with your openvpn conf
vm_name: 'my-awesome-vm' # name of the vm
upgrade_on_playbook: true # upgrade vm on playbook, can be very long, use vagrant box update if possible. box is automatically upgraded when run with unattended upgrades.
intnet_dhcp: true # use an intnet vbox with dhcp
enabled_vpn: true # enable vpn at startup
autologin: true # do not prompt login on lightdm
no_screen_lock: true # disable lock screen (useful for vms with a complex password)
local_domains: mydmz mydomain # domains to resolve with local dns (to work with vpn). Be carefaul, this can lead to dns leak if you resolve a public domain.
dns:
  fallback: 8.8.8.8 9.9.9.9 # fallback dns servers
  hosts: | # config to add on /etc/hosts
    192.168.1.66 awesome.local
  nosec: false # set to true to disable dnssec
