#!/usr/bin/env ansible-playbook

- name: 'set kali vm'
  hosts: all
  remote_user: vagrant
  become: yes
  vars_files:
    - vault.yml
    - config.yml

  roles:
    - role: 'roles/local_apt_proxy'
    - role: 'ntp'
    - role: 'roles/common'
    - role: 'roles/no-screen-lock'
    - role: 'roles/autologin'
    - role: 'roles/ufw'
    - role: 'roles/set_victim'
    - role: 'roles/locale'
    - role: 'roles/guake'
    - role: 'roles/vpn'
    - role: 'roles/unattented_upgrades'
    - role: 'roles/alias'
    - role: 'roles/sbd'
    - role: 'roles/vendor'
    - role: 'roles/tor'
    - role: 'discovery'

    - role: 'roles/git_sources'
    - role: 'roles/apache'
    - role: 'roles/peda'

  tasks:
    - name: upgrade packages
      apt:
        update_cache: true
        upgrade: 'dist'
        autoclean: true
        autoremove: true
      when: upgrade_on_playbook
