---
- name: install shodan client
  apt:
    name: python3-shodan
    state: present

- name: Create directory '/home/{{ default_user }}/.config'
  file:
    path: '/home/{{ default_user }}/.config/shodan'
    state: directory
    owner: '{{ default_user }}'
    mode: '0700'

- name: set shodan key
  copy:
    dest: '/home/{{ default_user }}/.config/shodan/api_key'
    content: '{{ shodan_api_key }}'
    owner: '{{ default_user }}'
    mode: '0600'
  when: shodan_api_key is defined

- name: install censys client
  apt:
    name: python3-censys
    state: present

- name: configure censys api
  blockinfile:
    path: '/home/{{ default_user }}/.zshrc'
    state: present
    block: |
      export CENSYS_API_ID={{ censys_api_id }}
      export CENSYS_API_SECRET={{ censys_api_secret }}
  when: censys_api_id is defined and censys_api_secret is defined
