- name: install openvpn
  apt:
    name: openvpn
    install_recommends: yes
    update_cache: yes
  when: vpn_name is defined and vpn_name != None

- name: copy default config
  template:
    src: files/etc/default/openvpn.j2
    dest: /etc/default/openvpn
  when: vpn_name is defined and vpn_name != None
  notify: daemon reload

- name: copy auth file
  template:
    src: templates/auth.txt.j2
    dest: /etc/openvpn/auth.txt
    mode: '0400'
  when: vpn_name is defined and vpn_name != None
  notify: daemon reload

- name: add vpn file
  copy:
    src: 'openvpn/'
    dest: /etc/openvpn/
    mode: '0400'
  when: vpn_name is defined and vpn_name != None
  notify: daemon reload

- name: disable openvpn
  systemd:
    name: openvpn
    enabled: false
  when: vpn_name is defined and vpn_name != None and not enabled_vpn

- name: enable openvpn
  systemd:
    name: openvpn
    enabled: true
  when: vpn_name is defined and vpn_name != None and enabled_vpn
