- name: install openvpn
  apt:
    name: openvpn,openvpn-systemd-resolved
    install_recommends: yes
    update_cache: yes
  when: vpn_name is defined and vpn_name != None

- name: ensure resolvconf is absent
  apt:
    name: resolvconf
    state: absent

- name: copy default config
  template:
    src: files/etc/default/openvpn.j2
    dest: /etc/default/openvpn
  when: vpn_name is defined and vpn_name != None
  notify: daemon reload

- name: copy nofallback scripts
  template:
    src: 'files/etc/openvpn/{{ item }}'
    dest: /etc/openvpn/
    mode: '0755'
  when: vpn_name is defined and vpn_name != None
  loop:
    - remove_fallback_conf
    - set_no_fallback
  notify: daemon reload

- name: copy auth file
  template:
    src: templates/auth.txt.j2
    dest: /etc/openvpn/auth.txt
    mode: '0400'
  when: vpn_name is defined and vpn_name != None
  notify: daemon reload

- name: add vpn file
  copy:
    src: 'openvpn/'
    dest: /etc/openvpn/
    mode: '0400'
  when: vpn_name is defined and vpn_name != None
  notify: daemon reload

- name: disable openvpn
  systemd:
    name: openvpn
    enabled: false
    state: stopped
  when: vpn_name is defined and vpn_name != None and (enabled_vpn is not defined or not enabled_vpn)

- name: enable openvpn
  systemd:
    name: openvpn
    enabled: true
    state: started
  when: vpn_name is defined and vpn_name != None and enabled_vpn is defined and enabled_vpn
