- name: install openvpn
  apt:
    name: openvpn,openvpn-systemd-resolved
    install_recommends: yes
    update_cache: yes
  when: vpn.name is defined and vpn.name != None

- name: copy default config
  template:
    src: files/etc/default/openvpn.j2
    dest: /etc/default/openvpn
  when: vpn.name is defined and vpn.name != None
  notify: daemon reload

- name: copy auth file
  template:
    src: templates/auth.txt.j2
    dest: /etc/openvpn/auth.txt
    mode: '0400'
  when: vpn.name is defined and vpn.name != None
  notify: daemon reload

- name: add vpn file
  copy:
    src: 'openvpn/'
    dest: /etc/openvpn/
    mode: '0400'
  when: vpn.name is defined and vpn.name != None
  notify: daemon reload

- name: disable openvpn
  systemd:
    name: openvpn
    enabled: false
    state: stopped
  when: vpn.name is defined and vpn.name != None and (vpn.enabled is not defined or not vpn.enabled)

- name: enable openvpn
  systemd:
    name: openvpn
    enabled: true
    state: started
  when: vpn.name is defined and vpn.name != None and vpn.enabled is defined and vpn.enabled
