- name: install openvpn
  apt:
    name: openvpn,openvpn-systemd-resolved
    install_recommends: yes
    update_cache: yes
  when: vpn_name is defined and vpn_name != None

- name: ensure resolvconf is absent
  apt:
    name: resolvconf
    state: absent

- name: disable network-manager
  systemd:
    name: NetworkManager
    enabled: false
    state: stopped

- name: ensure systemd-resolved is started
  systemd:
    name: systemd-resolved
    state: started
    enabled: true

- name: 'custom dns configuration'
  copy:
    dest: /etc/systemd/resolved.conf.d/dns.conf
    content: |
      [Resolve]
      FallbackDNS=9.9.9.9 1.1.1.1 149.112.112.112 1.0.0.1 2620:fe::fe 2606:4700:4700::1111 2620:fe::9 2606:4700:4700::1001
  notify: reload systemd-resolved

- name: set link to /etc/resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: copy default config
  template:
    src: files/etc/default/openvpn.j2
    dest: /etc/default/openvpn
  when: vpn_name is defined and vpn_name != None
  notify: daemon reload

- name: copy auth file
  template:
    src: templates/auth.txt.j2
    dest: /etc/openvpn/auth.txt
    mode: '0400'
  when: vpn_name is defined and vpn_name != None
  notify: daemon reload

- name: add vpn file
  copy:
    src: 'openvpn/'
    dest: /etc/openvpn/
    mode: '0400'
  when: vpn_name is defined and vpn_name != None
  notify: daemon reload

- name: disable openvpn
  systemd:
    name: openvpn
    enabled: false
    state: stopped
  when: vpn_name is defined and vpn_name != None and (enabled_vpn is not defined or not enabled_vpn)

- name: enable openvpn
  systemd:
    name: openvpn
    enabled: true
    state: started
  when: vpn_name is defined and vpn_name != None and enabled_vpn is defined and enabled_vpn
