---
- name: ensure resolvconf and dnsmasq is absent
  apt:
    name: resolvconf,systemd-resolved
    state: absent

- name: Prevent systemd-resolved from being installed
  ansible.builtin.dpkg_selections:
    name: systemd-resolved
    selection: hold

- name: Prevent dhcp to modify /etc/resolv.conf
  copy:
    dest: /etc/dhcp/dhclient-enter-hooks.d/nodnsupdate
    content: |
      #!/bin/sh
      make_resolv_conf() {
        :
      }
    mode: '0755'

- name: ensure NetworkManager and dnsmasq are installed
  apt:
    name: network-manager,dnsmasq
    state: present

- name: Disable dns config for NetworkManager
  copy:
    dest: /etc/NetworkManager/conf.d/00-nodns.conf
    content: |
      [main]
      dns=none
    mode: '0644'
  notify:
    - Reload dnsmasq

- name: Enable dnssec configuration
  copy:
    dest: /etc/dnsmasq.d/30-dnssec.conf
    content: |
      dnssec
  notify:
    - Reload dnsmasq
  when: dns.nosec is not defined or not dns.nosec

- name: Disallow custom dnssec configuration
  file:
    path: /etc/dnsmasq.d/30-dnssec.conf
    state: absent
  notify:
    - Reload dnsmasq
  when: dns.nosec is defined and dns.nosec

- name: Set Upstream dns configuration
  template:
    src: templates/upstream.conf.j2
    dest: /etc/dnsmasq.d/50-upstream.conf
  notify:
    - Reload dnsmasq
  when: dns.upstream is defined

- name: Set add hosts on dnsmasq
  copy:
    dest: /etc/dnsmasq.d/hosts.conf
    content: |
      addn-hosts=/etc/hosts.custom
      no-resolv
  notify:
    - Reload dnsmasq

- name: add hosts config
  copy:
    dest: /etc/hosts.custom
    content: "{{ dns.hosts | default('') }}"

- name: Ensure network-manager is started
  systemd:
    name: NetworkManager
    enabled: true
    state: started

- name: flush handlers
  meta: flush_handlers

- name: Set /etc/resolv.conf
  copy:
    dest: /etc/resolv.conf
    content: |
      # Generated via ansible provision
      nameserver 127.0.0.1
    mode: '0444'
