---
- name: ensure resolvconf is absent
  apt:
    name: resolvconf
    state: absent

- name: ensure NetworkManager is installed
  apt:
    name: network-manager
    state: present

- name: Enable network-manager
  systemd:
    name: NetworkManager
    enabled: true
    state: started

- name: make NetworkManager symlink
  file:
    src: /run/NetworkManager/resolv.conf
    dest: /etc/revolv.conf
    state: link
  notify:
    - Restart NetworkManager

- name: Ensure /etc/NetworkManager is present
  copy:
    dest: /etc/NetworkManager/conf.d/00-dnsmasq.conf
    content: |
      [main]
      dns=dnsmasq
      rc-manager=symlink
    mode: '0755'
  notify:
    - Restart NetworkManager

- name: 'custom dnssec configuration'
  template:
    src: templates/dnssec.conf.j2
    dest: /etc/NetworkManager/dnsmasq.conf.d/dnssec.conf
  notify:
    - Restart NetworkManager
  when: dns.nosec is not defined or not dns.nosec

- name: 'fallback dns configuration'
  template:
    src: templates/fallback.conf.j2
    dest: /etc/NetworkManager/dnsmasq.conf.d/fallback.conf
  notify:
    - Restart NetworkManager
  when: dns.fallback is defined

- name: 'fallback dns configuration'
  copy:
    dest: /etc/NetworkManager/dnsmasq.conf.d/hosts.conf
    content: |
      addn-hosts=/etc/hosts.custom
  notify:
    - Restart NetworkManager
  when: dns.fallback is defined

- name: add hosts config
  blockinfile:
    path: /etc/hosts.custom
    block: '{{ dns.hosts }}'
  when: dns.hosts is defined
