---
- name: ensure resolvconf is absent
  apt:
    name: resolvconf
    state: absent

- name: disable network-manager
  systemd:
    name: NetworkManager
    enabled: false
    state: stopped

- name: ensure systemd-resolved is started
  systemd:
    name: systemd-resolved
    state: started
    enabled: true

- name: 'custom dns configuration'
  copy:
    dest: /etc/systemd/resolved.conf.d/dns.conf
    content: |
      [Resolve]
      FallbackDNS={{ dns.fallback }}
  notify: reload systemd-resolved

- name: 'set dnssec'
  copy:
    dest: /etc/systemd/resolved.conf.d/dnssec.conf
    content: |
      [Resolve]
      DNSSEC=true
  notify: reload systemd-resolved
  when: dns.nosec is not defined and dns.nosec

- name: 'use local network resolution'
  copy:
    dest: /etc/systemd/network/50-dhcp.network
    content: |
      [Match]
      Name=eth0
      
      [Network]
      DHCP=yes
      Domains={{ local_domains }}
  notify: reload systemd-networkd
  when: local_domains is defined and local_domains

- name: set link to /etc/resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: add hosts config
  blockinfile:
    path: /etc/hosts
    block: '{{ dns.hosts }}'
