- name: 'add user {{ default_user }}'
  user:
    name: '{{ default_user }}'
    state: present
    create_home: true
    password: '{{ user_shadow }}'
    generate_ssh_key: true
    shell: /usr/bin/zsh
    groups:
      - sudo

- name: 'update user vagrant'
  user:
    name: vagrant
    state: present
    password: '{{ vagrant_shadow }}'
    password_lock: true


- name: 'Set timezone to {{ timezone }}'
  community.general.timezone:
    name: '{{ timezone }}'

- name: ensure kali-grant-root is removed
  apt:
    name: kali-grant-root
    state: absent
    autoclean: true
    autoremove: true
    purge: true

- name: add kali defaults
  apt:
    name: kali-defaults
    state: present
    update_cache: yes

- name: add useful packages (bettercap,git, firefox, ncat, gobuster, seclists, htop, ascii, wpscan)
  apt:
    name: bettercap,git,firefox-esr,ncat,gobuster,seclists,htop,ascii,wpscan
    state: present
    update_cache: yes

- name: Ensure burpsuite community is removed (to install pro version)
  apt:
    name: burpsuite
    state: absent
    update_cache: yes
    autoremove: yes
    autoclean: yes

- name: ensure firefox policies are present
  copy:
    src: files/policies.json
    dest: /usr/share/firefox-esr/distribution/policies.json

- name: set git user email
  git_config:
    name: user.email
    scope: global
    value: '{{ git_email }}'
  become_user: '{{ default_user }}'

- name: set git user name
  git_config:
    name: user.name
    scope: global
    value: '{{ git_user }}'
  become_user: '{{ default_user }}'

- name: set git rebase strategy
  git_config:
    name: pull.rebase
    scope: global
    value: 'true'
  become_user: '{{ default_user }}'

- name: Extend sudo timeout
  template:
    src: 'files/timeout.j2'
    dest: /etc/sudoers.d/timeout
    mode: '0400'

- name: enable autologin
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    line: 'autologin-user={{ default_user }}'
  when: autologin is defined and autologin

- name: enable autologin
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    line: 'autologin-user-timeout=0'
  when: autologin is defined and autologin
